source "https://rubygems.org"

gem "dotenv",       "~>2.2.1"
gem "puma",         "~>3.11.3"
gem "rack",         "~>2.0.4"
gem "rake",         "~>12.3.1"
gem "redcarpet",    "~>3.4.0"
gem "rspec",        "~>3.7.0"
gem "sinatra",      "~>2.0.3"
gem "slim",         "~>3.0.9"